ALTER TABLE "inspections" ADD COLUMN "submitted_by_auth_user_id" uuid;
--> statement-breakpoint
ALTER TABLE "inspections" ADD COLUMN "submitted_by_email" varchar(320);
--> statement-breakpoint
ALTER TABLE "inspections" ADD COLUMN "submitted_at" timestamp with time zone;
--> statement-breakpoint
ALTER TABLE "inspection_area_inspections" ADD COLUMN "is_skipped" boolean DEFAULT false NOT NULL;
--> statement-breakpoint
ALTER TABLE "inspection_area_inspections" ADD COLUMN "skip_reason" varchar(1000);
--> statement-breakpoint
ALTER TABLE "inspection_items" ADD COLUMN "result_status" varchar(24);
--> statement-breakpoint
ALTER TABLE "inspection_items" ADD COLUMN "result_note" varchar(1000);
--> statement-breakpoint
UPDATE "inspections"
SET
	"submitted_by_auth_user_id" = COALESCE("submitted_by_auth_user_id", "started_by_auth_user_id"),
	"submitted_by_email" = COALESCE("submitted_by_email", "started_by_email"),
	"submitted_at" = COALESCE("submitted_at", "updated_at", "started_at")
WHERE "status" = 'submitted';
--> statement-breakpoint
CREATE TABLE "tickets" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ticket_number" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"status" varchar(24) DEFAULT 'open' NOT NULL,
	"title" varchar(340) NOT NULL,
	"inspection_id" uuid NOT NULL,
	"area_inspection_id" uuid NOT NULL,
	"inspection_item_id" uuid NOT NULL,
	"client_id" uuid NOT NULL,
	"building_id" uuid NOT NULL,
	"area_id" uuid NOT NULL,
	"created_by_auth_user_id" uuid NOT NULL,
	"created_by_email" varchar(320) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "tickets_status_valid" CHECK ("tickets"."status" in ('open', 'closed')),
	CONSTRAINT "tickets_title_not_blank" CHECK (length(btrim("tickets"."title")) > 0)
);
--> statement-breakpoint
ALTER TABLE "inspections" ADD CONSTRAINT "inspections_submission_metadata_matches_status" CHECK ((
        "inspections"."status" = 'draft'
        and "inspections"."submitted_by_auth_user_id" is null
        and "inspections"."submitted_by_email" is null
        and "inspections"."submitted_at" is null
      ) or (
        "inspections"."status" = 'submitted'
        and "inspections"."submitted_by_auth_user_id" is not null
        and "inspections"."submitted_by_email" is not null
        and "inspections"."submitted_at" is not null
      ));
--> statement-breakpoint
ALTER TABLE "inspection_area_inspections" ADD CONSTRAINT "inspection_area_inspections_skip_state_valid" CHECK ((
        "inspection_area_inspections"."is_skipped" = false and "inspection_area_inspections"."skip_reason" is null
      ) or (
        "inspection_area_inspections"."is_skipped" = true
        and "inspection_area_inspections"."source" = 'planned'
        and "inspection_area_inspections"."skip_reason" is not null
        and length(btrim("inspection_area_inspections"."skip_reason")) > 0
      ));
--> statement-breakpoint
ALTER TABLE "inspection_items" ADD CONSTRAINT "inspection_items_result_status_valid" CHECK ("inspection_items"."result_status" is null or "inspection_items"."result_status" in ('pass', 'fail', 'not_applicable'));
--> statement-breakpoint
ALTER TABLE "inspection_items" ADD CONSTRAINT "inspection_items_result_note_not_blank" CHECK ("inspection_items"."result_note" is null or length(btrim("inspection_items"."result_note")) > 0);
--> statement-breakpoint
ALTER TABLE "tickets" ADD CONSTRAINT "tickets_inspection_id_inspections_id_fk" FOREIGN KEY ("inspection_id") REFERENCES "public"."inspections"("id") ON DELETE restrict ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "tickets" ADD CONSTRAINT "tickets_area_inspection_id_inspection_area_inspections_id_fk" FOREIGN KEY ("area_inspection_id") REFERENCES "public"."inspection_area_inspections"("id") ON DELETE restrict ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "tickets" ADD CONSTRAINT "tickets_inspection_item_id_inspection_items_id_fk" FOREIGN KEY ("inspection_item_id") REFERENCES "public"."inspection_items"("id") ON DELETE restrict ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "tickets" ADD CONSTRAINT "tickets_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE restrict ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "tickets" ADD CONSTRAINT "tickets_building_id_buildings_id_fk" FOREIGN KEY ("building_id") REFERENCES "public"."buildings"("id") ON DELETE restrict ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "tickets" ADD CONSTRAINT "tickets_area_id_areas_id_fk" FOREIGN KEY ("area_id") REFERENCES "public"."areas"("id") ON DELETE restrict ON UPDATE no action;
--> statement-breakpoint
CREATE INDEX "tickets_status_idx" ON "tickets" USING btree ("status");
--> statement-breakpoint
CREATE INDEX "tickets_inspection_id_idx" ON "tickets" USING btree ("inspection_id");
--> statement-breakpoint
CREATE INDEX "tickets_client_id_idx" ON "tickets" USING btree ("client_id");
--> statement-breakpoint
CREATE INDEX "tickets_building_id_idx" ON "tickets" USING btree ("building_id");
--> statement-breakpoint
CREATE INDEX "tickets_area_id_idx" ON "tickets" USING btree ("area_id");
--> statement-breakpoint
CREATE UNIQUE INDEX "tickets_ticket_number_unique" ON "tickets" USING btree ("ticket_number");
--> statement-breakpoint
CREATE UNIQUE INDEX "tickets_inspection_item_id_unique" ON "tickets" USING btree ("inspection_item_id");
--> statement-breakpoint
ALTER TABLE "tickets" ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
REVOKE ALL ON TABLE "tickets" FROM anon;
--> statement-breakpoint
REVOKE ALL ON TABLE "tickets" FROM authenticated;
